FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Configure args ----------------------------------------------------------------------
ARG ENV_NAME

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID

ARG DB_ROOT_PATH

ARG SKIP_SEED
ARG SEED_FILE_CLOUD_PATH
ARG SEED_FILE_BUCKET

ARG AUDIO_STORAGE_BASE_STORAGE

ARG DIALOGFLOW_SESSION_BASE_PATH
ARG DIALOGFLOW_TARGET_PAGE

ARG CLOUD_CREDENTIALS_JSON

ARG PORT
ARG CHEAT
# ------------------------------------------------------------------------------------

# Set environments
ENV ENV_NAME=$ENV_NAME

ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID

ENV DB_ROOT_PATH=$DB_ROOT_PATH

ENV SKIP_SEED=$SKIP_SEED
ENV SEED_FILE_CLOUD_PATH=$SEED_FILE_CLOUD_PATH
ENV SEED_FILE_BUCKET=$SEED_FILE_BUCKET

ENV AUDIO_STORAGE_BASE_STORAGE=$AUDIO_STORAGE_BASE_STORAGE

ENV DIALOGFLOW_SESSION_BASE_PATH=$DIALOGFLOW_SESSION_BASE_PATH
ENV DIALOGFLOW_TARGET_PAGE=$DIALOGFLOW_TARGET_PAGE

ENV CLOUD_CREDENTIALS_JSON=$CLOUD_CREDENTIALS_JSON

ENV PORT=$PORT
ENV CHEAT=$CHEAT

# Install dependencies
RUN npm ci && npm run prepare-frontend && npm run prepare-server
# If you are building your code for production
# RUN npm ci --omit=dev

EXPOSE 8080
CMD [ "node", "./server/dist/app.js" ]
