FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Set environment variables
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG ENV_NAME
ARG ALLOW_SEED
ARG DB_ROOT_PATH
ARG PORT
ARG CHEAT

ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV ENV_NAME=$ENV_NAME
ENV ALLOW_SEED=$ALLOW_SEED
ENV DB_ROOT_PATH=$DB_ROOT_PATH
ENV PORT=$PORT
ENV CHEAT=$CHEAT

RUN npm ci && npm run prepare-frontend && npm run prepare-server
# If you are building your code for production
# RUN npm ci --omit=dev

EXPOSE 8080
CMD [ "node", "./server/dist/app.js" ]
