import { AppUser, Authenticator } from "../ApiSupport/authentication";
import { Request } from "express";
import { ApiErrorResponse } from "../ApiSupport/apiErrorHelpers";
import Result from "../ApiSupport/Result";
import { dynamicMessages } from "../ApiSupport/apiMessages";

export default class BaseController {
  private _user?: AppUser;
  private _authenticator: Authenticator;
  constructor(authenticator: Authenticator) {
    this._authenticator = authenticator;
  }

  public async authenticateAsync<T>(req: Request) {
    const authResult = await this._authenticator.getAuthUserFromReq(req);
    if (!authResult.isError()) {
      this._user = authResult.data;
      return;
    }
    throw ApiErrorResponse.ErrorResult(authResult.As<T>());
  }

  protected getUser(): AppUser {
    if (!this._user) {
      throw "Controller accessed 'User' while not doing prior authentication.";
    }
    return this._user;
  }

  private getSafeValueParam<T>(req: Request, key: string): string {
    const value = req.params?.[key];
    if (!value) {
      throw ApiErrorResponse.BadRequest<T>(
        dynamicMessages.requestParameterMissing(key)
      );
    }
    /**
     * Prevent security hazards. Clean the user input so no malicious parties access the Realtime database in unintended ways:
     * Ex: userStories/${id} -> 'id' should be a GUID, and not a sub-path to other resources!
     *
     * The GUIDs generated by the uuid package, such as UUID v4, do not contain any of the characters "/", ".", "#", "$", "[", "]" by default.
     * The UUIDs generated by the uuid package are represented as a string of alphanumeric characters and hyphens ("-") in the form of "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".
     */
    const safeValue = String(value)
      .split("")
      .filter(
        (x) =>
          !["/", ".", "#", "$", "[", "]"].some(
            (forbiddenChar) => forbiddenChar === x
          )
      )
      .join("");

    return safeValue;
  }

  public getParams<T>(req: Request, keys: string[]): string[] {
    const values: string[] = [];
    for (const key of keys) {
      const value = this.getSafeValueParam<T>(req, key);
      values.push(value);
    }
    return values;
  }

  protected processResult<T>(outputResult: Result<T>): T {
    if (outputResult.isError())
      throw ApiErrorResponse.ErrorResult(outputResult);
    return outputResult.data;
  }
}
